config/routes.rb
Tiviti::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  
  root :to => 'pages#home'  
  

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  
  # virual password attribute. This mean this attribute doesn't exist in the database but only in memory
  attr_accessor :password
  
  # public class memebers (accesible)
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  # validate that there's a name and email entered
  validates :name, :presence => true,
  				   :length   => { :maximum => 50 }
  validates :email, :presence => true,
 					:format   => { :with => email_regex },
 					:uniqueness => { :case_sensitive => false }
  
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
  
  # encrypt the password before saving the user to the Database
  before_save :encrypt_password
  
  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    # Compare encrypted_password with the encrypted version of
    # submitted_password.
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private

    def encrypt_password
    							#new_record? checks if the user already saved to the DB or not. We don't want to change the unique salt used to hash the password everytime the user is updated
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"     
  end

  def contact
    @title = "Contact"
  end
  
  def about    
    @title = "About"
  end
  
  def help
    @title = "Help"
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@title = "Sign In"
	end

	def create
    	user = User.authenticate(params[:session][:email],
        	                     params[:session][:password])
	    if user.nil?
	      flash.now[:error] = "Invalid email/password combination."
	      @title = "Sign in"
	      render 'new'
	    else
	      	# Sign the user in and redirect to the user's show page.
	      	sign_in user
      		redirect_back_or user 
	    end
	end
	
	def destroy
		sign_out
    	redirect_to root_path
    end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  	# prevent none-authenticated users from accessing edit & update functions
  	before_filter :authenticate, :only => [:index, :edit, :update]
  	# make sure users can only edit their own settings, not someone else's. If user try to go to users/2/edit they'll be redirected to root/home page 
  	before_filter :correct_user, :only => [:edit, :update]
  
  	# make sure attackers cannot access the delete user function. Only admin can get to it if signed in
  	before_filter :admin_user,   :only => :destroy
  
	# this function used to display all users in the DB in the index.html.erb page
	def index
		@title = "All users"
		@users = User.paginate(:page => params[:page])
	end
	
	# define the show function to display a user on the web page using show.html.erb (temp)
	def show
		@user = User.find(params[:id])
		@title = @user.name
	end
	  
	def new
		@user = User.new
		@title = "Sign up"
	end
	
	def create
	    @user = User.new(params[:user])
	    if @user.save
	    	flash[:success] = "Welcome to tiviti!"
	    	#redirect_to @user
	    	redirect_to signin_path
	    else
	      @title = "Sign up"
	      render 'new'
	    end
	end
	
	def edit
	    #@user = User.find(params[:id])
	    @title = "Edit user"
  	end
  	
  	def update
  		# don't need to set @user since correct_user is called every time (top) and already defines the @user variable
		#@user = User.find(params[:id])
	    if @user.update_attributes(params[:user])
	      flash[:success] = "Profile updated."
	      redirect_to @user
	    else
	      @title = "Edit user"
	      render 'edit'
	    end
	end
	 
	# correspond to the delete function for admin to delete a user (in index.html.erb page)
	def destroy
	    User.find(params[:id]).destroy
	    flash[:success] = "User destroyed."
	    redirect_to users_path
  	end
   
	private
	
		def authenticate
	    	deny_access unless signed_in?
	    end
    
	    def correct_user
	    	@user = User.find(params[:id])
	    	redirect_to(root_path) unless current_user?(@user)
	    end
	    
	    # local function to ensure only admin users can execute the delete/destroy function. If anyone
	    # other than admin try to access the destroy function, s/he'll be redirected to root path (home page)
	    def admin_user
    		redirect_to(root_path) unless current_user.admin?
    	end
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "tiviti"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
   def logo
		image_tag("tiviti-logo.jpg", :alt => "tiviti", :class => "round")
   end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end
	
	# defining the current_user variable and asigning value to it
	def current_user=(user)
		@current_user = user
  	end
  
	# returning the current_user valiable (looks duplicated to the one above but both are enccesary)
	def current_user
		# set the @current_user instance variable to the user corresponding to the remember token, but only if @current_user is undefined
		@current_user ||= user_from_remember_token
  	end

	def signed_in?
		!current_user.nil?
	end
  
	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
	# check is user is the current logged in user
	def current_user?(user)
    	user == current_user
  	end
  
	# used to make sure only authenticated users can access users update/edit functions
	def deny_access
		# store location for forwarding users after log in to their intended location
		store_location
    	redirect_to signin_path, :notice => "Please sign in to access this page."
  	end  
    
	# store location for forwarding users after log in to their intended location
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		clear_return_to
	end
  
  	private

		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
		end
	
	    def remember_token
	      cookies.signed[:remember_token] || [nil, nil]
	    end
	
		# user session cookie to store location for forwarding users after log in to their intended location
		def store_location
			session[:return_to] = request.fullpath
	    end
	
		# clear session cookie used to store location for forwarding users after log in to their intended location
	    def clear_return_to
			session[:return_to] = nil
	    end
end

app/helpers/users_helper.rb
module UsersHelper
	
	def gravatar_for(user, options = { :size => 50 })
    
    	gravatar_image_tag(user.email.downcase, :alt => user.name,
        	                                    :class => 'gravatar',
            	                                :gravatar => options)
  	end
	
end

app/views/layouts/JonHeader.html.erb
<!-- START MASTHEAD -->

<!-- this is the structure and background behind everything in the general header area -->
<div class="masthead">
          <center>
		<table>
  			<tr>
    			<td>&nbsp;
    			</td>
    			<td style="width: 920">

            <!-- START HEADER AREA -->

            <div class="header">
            <table width="100%">
            <tr>
            <!-- START LOGO CEL -->
            <td align="center" width="15%">
            	<a href="index.html">
	            <img src="images/logo_tiviti.png" border="0" width="112" height="52"></a>
            </td>

            <!-- END LOGO CEL -->

            <td width="60%" align="center">

          	<!-- START NAVIGATION -->

      		<div class="nav">
      		<table width="100%">
   			<tr>
	   			<td width="20%" align="center">
        			<b>
             			<font color="#CCFF99">home
                			</font>
                			</b>
                			</td>
                			<td width="20%" align="center">
                			<font>
                			<a href="activities.html">all activities</a>
                			</font>
                			</td>
                			<td width="20%" align="center">
                			<font>
                			<a href="myteam.html">my team</a>
                			</font>
                			</td>
                			<td width="20%">&nbsp;
                			</td>
                			<td width="20%">&nbsp;
                			</td>
              			</tr>
          			</table>
          			</div>
  	
          			<!-- END NAVIGATION -->
         	
                </td>
                <td width="25%" align="right">
				<!-- START AUXILIARY NAV -->
      			<table>
        			<tr>
          			<td valign="bottom">
          			<p align="right"><b><font>Jon Nakasone</font></b></font></td>
          			<td rowspan="2" width="2"></td>
          			<td rowspan="2">
          			<img border="0" src="images/avatar2.jpg" width="50" height="50"></td>
          			</tr>
        			<tr>
          			<td valign="top">
          			<p align="right"><font>
          			<a href="account.html">my account</a>&nbsp; <font color="#CCCCCC">|
          			</font>&nbsp;<a href="signout.html">sign out</a></font></td>
        			</tr>
      			</table>
      
      			<!-- END AUXILIARY NAV -->
      
                	</td>
              	</tr>
          	</table>
          	</div>
          	
	      	<!-- END HEADER AREA -->
          	
    		</td>
    		<td>&nbsp;</td>
  			</tr>
  		</table>
	      </center>
        </div>
	</div>

<!-- END MASTHEAD -->

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <!-- no need for header link since titivi logo is linked to it>
      	<li><%= link_to "Home", root_path %></li>
      -->
      
       <% if signed_in? %>
      		<li><%= link_to "Users", users_path %></li>       
       <% end %>
       
      <li><%= link_to "Help", help_path %></li>
      
      <% if signed_in? %>
      	<li><%= link_to "Profile", current_user %></li>
      	<li><%= link_to "Settings", edit_user_path(current_user) %></li>
	  <% end %>
      
      <% if signed_in? %>
      	<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      		<li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>          
  </nav>
</header>

app/views/layouts/_mainnav.html.erb
<!--   
   <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="100%">
       <tr>
          <td width="100%">
          <div align="center">
            <center>
            <div class="nav">
            <table>
              <tr>
                <td>
                <b>
                    <font color="#CCFF99">
                    home</font></b></td>
                <td>
                <font><a href="activities.html">all activities</a></font></td>
                <td>
                <font><a href="myteam.html">my team</a></font></td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
              </tr>
            </table>
            </center>
          </div>
          </td>
        </tr>
        </table>
-->

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->


<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>


<!--<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->



<%= stylesheet_link_tag 'tiviti-global', :media => 'screen' %>



<!-- Jon's Stylesheets 
<%= stylesheet_link_tag 'activity', :media => 'screen' %>
<%= stylesheet_link_tag 'global', :media => 'screen' %>
<%= stylesheet_link_tag 'header', :media => 'screen' %>
<%= stylesheet_link_tag 'masthead', :media => 'screen' %>
<%= stylesheet_link_tag 'nav', :media => 'screen' %>
<%= stylesheet_link_tag 'nav-auxiliary', :media => 'screen' %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  
  <body>
    
    <div class="container">
      <header>
        <%= render 'layouts/header' %>
      </header>
      
      <%= render 'layouts/mainnav' %>
      
      <section class="round">
      	
      	<!--a message that appears temporarily and then disappears upon page reload-->
      	<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <!-- -->
        
        <%= yield %>
        
      </section>
      
      
      <!-- Here's some debug stuff that will show on the application, not the if statement, only for development env. -->
      <%= debug(params) if Rails.env.development? %>
      
      
      
      <%= render 'layouts/footer' %>
       
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
   <a href="http://railstutorial.org/">more information later</a>
   some text goes here
   with <a href="http://rubyonrails.org/">get stuff done</a>. This
   more text after the link
</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>
  Contact our team
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  The tiviti support team is currently surfing....please try again later or just try figure it out yourself as we spent a lot of time to make this product easy to use for people like you....
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<h1>Get stuff done faster!</h1>
<div class="activity" align="left">
<table width="100%" style="border-collapse: collapse" bordercolor="#111111" cellpadding="3" cellspacing="0">
              <tr>
                <td width="40">
                <p align="center"><img border="0" src="images/avatar4.jpg" width="35" height="35"></td>
                <td>
                <p align="left"><font><a href="profile-tiviti.html">Team Tiviti</a> 
                needs your help with <a href="activity_detail.html">completing your profile</a></font></b></td>
                <td width="1%">
                <p align="left"><img border="0" src="images/divider.jpg" width="1" height="35"></td>
                <td width="4%" align="left">
                <p>
                <img border="0" src="images/status-off.jpg" width="16" height="16"></td>
              </tr>
            </table>
</div>
<p>
   This is the home page for the
   <a href="http://railstutorial.org/">get stuff done with titivi</a>
   sample application.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<!-- using object to generalize form to handel any type of object -->
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  
  <% if current_user.admin? %>
  | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
  <% end %>
  
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<!-- A page to display all users in the database -->
<h1>All users</h1>

<%= will_paginate %>


<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<!-- we can eliminate the loop above by doing render right on the @users variable. I didn't do it sinse 
	it's not as clear from code perspective - which partical (_user.html.erb is being rendered)

<ul class="users">
  <%= render @users %>
</ul>

-->

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>

	<%= render 'shared/error_messages', :object => f.object %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
	
<% end %>

app/views/users/show.html.erb
<!--# just a dummy page to show user information temporary--> 

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
    	<h1>
			<%= gravatar_for @user %>
			<%= @user.name %> 
		</h1>
		<%= @user.email %>
	</td>
    <td class="sidebar round">
      <strong>Name:</strong> <%= @user.name %><br />
      <strong>URL:</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>